"use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import classNames from "classnames";

import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import React from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dutiful Test App",
  description: "Generated by Aaron Sunday",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [queryClient] = React.useState(() => new QueryClient());
  return (
    <html lang="en">
      <QueryClientProvider client={queryClient}>
        
        <body className={classNames(inter.className)}>
          <Header />
          {children}
          <Footer />
        </body>
      </QueryClientProvider>
    </html>
  );
}
